steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    env:
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=$AIzaSyCU687LeYH-480qcPia30RKcio48szfHek'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$flipcards-448722.firebaseapp.com'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=$flipcards-448722'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$flipcards-448722.appspot.com'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$356140602370'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=$1:356140602370:web:ae7ddab5d7254b7dc7831b'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'export'] # Optional: if you're statically exporting the site

images: []